inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - "tmp/**/*"
    - "config/initializers/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "db/migrate/*.rb"
    - "bin/*"
  TargetRubyVersion: 2.5.3

GitHub/RailsControllerRenderPathsExist:
  Enabled: false
